# This is the default format.
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:year/:month/:day/:title

exclude: [".rvmrc", ".rbenv-version", "ReadMe.md", "Rakefile", "changelog.md", "License.md"]
highlighter: rouge

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title : source site
author :
  name : San
  email : jack5010485@gmail.com
  github : oicjacky
  twitter : oicjacky
  feedburner : oicjacky

# NOTE: Replacing this next line with your own URL
production_url : https://oicjacky.github.io/personal-site/

# Tell Github to use the kramdown markdown interpreter
# (see https://help.github.com/articles/migrating-your-pages-site-from-maruku)
markdown: kramdown


theme: jekyll-theme-merlot